In [1]:
import pandas as pd

In [2]:
Bank_data = pd.read_csv("dataset/European_Bank (1).csv")

In [3]:
Bank_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Year             10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  str
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  str
 5   Gender           10000 non-null  str
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), str(3)
memory usage: 1.1 MB

In [4]:
Bank_data.head()

,Year,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,2025,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2025,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,2025,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,2025,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,2025,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
Bank_data.tail()

,Year,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9995,2025,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,2025,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,2025,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,2025,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,2025,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [6]:
Bank_data.isnull().sum()

Year               0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [7]:
Bank_data.duplicated().sum()

np.int64(0)

In [8]:
Bank_data.duplicated(keep= False)

0       False
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

In [9]:
Bank_data.describe()

,Year,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.0,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,2025.0,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,0.0,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,2025.0,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2025.0,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,2025.0,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,2025.0,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,2025.0,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [10]:
Bank_data.drop(columns = "Surname")

,Year,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,2025,15634602,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2025,15647311,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,2025,15619304,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,2025,15701354,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,2025,15737888,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2025,15606229,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,2025,15569892,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,2025,15584532,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,2025,15682355,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,2025,15628319,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [11]:
Bank_data.groupby("Exited")["Balance"].mean()

Exited
0    72745.296779
1    91108.539337
Name: Balance, dtype: float64

In [12]:
Bank_data.groupby("Exited")["NumOfProducts"].mean()

Exited
0    1.544267
1    1.475209
Name: NumOfProducts, dtype: float64

In [13]:
Bank_data.groupby("Exited")["IsActiveMember"].mean()

Exited
0    0.554565
1    0.360825
Name: IsActiveMember, dtype: float64

In [14]:
Bank_data.groupby("Exited")["EstimatedSalary"].mean()

Exited
0     99738.391772
1    101465.677531
Name: EstimatedSalary, dtype: float64

In [15]:
Bank_data.groupby("Exited")["Age"].mean()

Exited
0    37.408389
1    44.837997
Name: Age, dtype: float64

In [16]:
Bank_data.drop(columns="Surname")

,Year,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,2025,15634602,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2025,15647311,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,2025,15619304,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,2025,15701354,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,2025,15737888,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2025,15606229,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,2025,15569892,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,2025,15584532,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,2025,15682355,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,2025,15628319,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [17]:
Bank_data.groupby(["Geography"])["Exited"].value_counts(normalize= True).loc[:, 1]*100

Geography
France     16.154767
Germany    32.443204
Spain      16.673395
Name: proportion, dtype: float64

In [18]:
Bins = [0,30,45,60,100]     # bins he lablel peksha 1 ni jasta pahije

Labels =["<30","31-45","46-60",">60"]

Bank_data["Age_group"] = pd.cut(Bank_data["Age"],bins=Bins,labels=Labels)

Bank_data

,Year,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Age_group
0,2025,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,31-45
1,2025,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,31-45
2,2025,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,31-45
3,2025,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,31-45
4,2025,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,31-45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2025,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0,31-45
9996,2025,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0,31-45
9997,2025,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1,31-45
9998,2025,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1,31-45
9999,2025,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0,<30

In [19]:
Bank_data.groupby("Age")["Age"].value_counts()

Age
18    22
19    27
20    40
21    53
22    84
      ..
83     1
84     2
85     1
88     1
92     2
Name: count, Length: 70, dtype: int64

In [20]:
Bank_data.groupby("Age_group")["Exited"].value_counts(normalize = True).loc[:,1]*100

Age_group
<30       7.520325
31-45    15.740584
46-60    51.123254
>60      24.784483
Name: proportion, dtype: float64

In [21]:
Bank_data.groupby(["Age_group","Geography"])["Exited"].value_counts(normalize = True).loc[:,:,1]*100

Age_group  Geography
<30        France        4.913295
           Germany      12.362031
           Spain         8.595388
31-45      France       12.349800
           Germany      26.092991
           Spain        12.533693
46-60      France       45.794393
           Germany      67.330677
           Spain        40.656566
>60        France       19.913420
           Germany      38.938053
           Spain        20.833333
Name: proportion, dtype: float64

In [22]:
Bins = [300,670,740,850]

Labels = ["Low","Medium","High"]

Bank_data["CreditScore_group"]= pd.cut(Bank_data["CreditScore"],bins=Bins,labels=Labels)

In [23]:
Bank_data

,Year,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Age_group,CreditScore_group
0,2025,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,31-45,Low
1,2025,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,31-45,Low
2,2025,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,31-45,Low
3,2025,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,31-45,Medium
4,2025,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,31-45,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2025,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0,31-45,High
9996,2025,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0,31-45,Low
9997,2025,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1,31-45,Medium
9998,2025,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1,31-45,High
9999,2025,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0,<30,High

In [24]:
Bank_data["Balance"].max()

np.float64(250898.09)

In [25]:
Bank_data["Tenure"].max()

np.int64(10)

In [26]:
Bank_data["Tenure"].mean()

np.float64(5.0128)

In [27]:
Bank_data["Tenure"].min()

np.int64(0)

In [41]:
Bins = [-1,2,5,10]

Labels = ["New_customer","Mid term","Long term"]

Bank_data["Tenure_group"] = pd.cut(Bank_data["Tenure"],bins=Bins,labels=Labels)

Bank_data

,Year,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Age_group,CreditScore_group,Tenure_group,Balance_group
0,2025,15634602,619,France,Female,42,2,0.00,1,1,1,101348.88,1,31-45,Low,New_customer,zero_balance
1,2025,15647311,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,31-45,Low,New_customer,Min_balance
2,2025,15619304,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,31-45,Low,Long term,High_balance
3,2025,15701354,699,France,Female,39,1,0.00,2,0,0,93826.63,0,31-45,Medium,New_customer,zero_balance
4,2025,15737888,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,31-45,High,New_customer,Min_balance
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2025,15606229,771,France,Male,39,5,0.00,2,1,0,96270.64,0,31-45,High,Mid term,zero_balance
9996,2025,15569892,516,France,Male,35,10,57369.61,1,1,1,101699.77,0,31-45,Low,Long term,Min_balance
9997,2025,15584532,709,France,Female,36,7,0.00,1,0,1,42085.58,1,31-45,Medium,Long term,zero_balance
9998,2025,15682355,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1,31-45,High,Mid term,Min_balance
9999,2025,15628319,792,France,Female,28,4,130142.79,1,1,0,38190.78,0,<30,High,Mid term,Min_balance

In [29]:
Bank_data["Balance"].max()

np.float64(250898.09)

In [30]:
Bank_data["Balance"].min()

np.float64(0.0)

In [31]:
Bank_data["Balance"].mean()

np.float64(76485.889288)

In [32]:
Bins = [-1,50000,150000,float("inf")]

Labels = ["zero_balance","Min_balance","High_balance"]

Bank_data["Balance_group"] = pd.cut(Bank_data["Balance"],labels= Labels,bins = Bins)

In [33]:
Bank_data

,Year,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Age_group,CreditScore_group,Tenure_group,Balance_group
0,2025,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,31-45,Low,New_customer,zero_balance
1,2025,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,31-45,Low,New_customer,Min_balance
2,2025,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,31-45,Low,Long term,High_balance
3,2025,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,31-45,Medium,New_customer,zero_balance
4,2025,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,31-45,High,New_customer,Min_balance
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2025,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0,31-45,High,Mid term,zero_balance
9996,2025,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0,31-45,Low,Long term,Min_balance
9997,2025,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1,31-45,Medium,Long term,zero_balance
9998,2025,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1,31-45,High,Mid term,Min_balance
9999,2025,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0,<30,High,Mid term,Min_balance

In [34]:
Bank_data.drop(columns="Surname",inplace=True)

In [35]:
Bank_data

,Year,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Age_group,CreditScore_group,Tenure_group,Balance_group
0,2025,15634602,619,France,Female,42,2,0.00,1,1,1,101348.88,1,31-45,Low,New_customer,zero_balance
1,2025,15647311,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,31-45,Low,New_customer,Min_balance
2,2025,15619304,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,31-45,Low,Long term,High_balance
3,2025,15701354,699,France,Female,39,1,0.00,2,0,0,93826.63,0,31-45,Medium,New_customer,zero_balance
4,2025,15737888,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,31-45,High,New_customer,Min_balance
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2025,15606229,771,France,Male,39,5,0.00,2,1,0,96270.64,0,31-45,High,Mid term,zero_balance
9996,2025,15569892,516,France,Male,35,10,57369.61,1,1,1,101699.77,0,31-45,Low,Long term,Min_balance
9997,2025,15584532,709,France,Female,36,7,0.00,1,0,1,42085.58,1,31-45,Medium,Long term,zero_balance
9998,2025,15682355,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1,31-45,High,Mid term,Min_balance
9999,2025,15628319,792,France,Female,28,4,130142.79,1,1,0,38190.78,0,<30,High,Mid term,Min_balance

In [39]:
Bank_data.groupby("CreditScore_group")["Exited"].value_counts(normalize = True).loc[:,1]*100

CreditScore_group
Low       21.121365
Medium    18.815186
High      20.053763
Name: proportion, dtype: float64

In [36]:
Bank_data.to_csv("Bank_data_new_file.csv",index=False)

In [37]:
import os

In [38]:
os.getcwd()

'C:\\Users\\rupes\\Documents\\Python practice\\Panda'

In [40]:
Bank_data.tail()

,Year,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Age_group,CreditScore_group,Tenure_group,Balance_group
9995,2025,15606229,771,France,Male,39,5,0.00,2,1,0,96270.64,0,31-45,High,Mid term,zero_balance
9996,2025,15569892,516,France,Male,35,10,57369.61,1,1,1,101699.77,0,31-45,Low,Long term,Min_balance
9997,2025,15584532,709,France,Female,36,7,0.00,1,0,1,42085.58,1,31-45,Medium,Long term,zero_balance
9998,2025,15682355,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1,31-45,High,Mid term,Min_balance
9999,2025,15628319,792,France,Female,28,4,130142.79,1,1,0,38190.78,0,<30,High,Mid term,Min_balance

In [42]:
Bank_data.to_csv('Bank_data_new_file.csv', index=False)